// LINE binding state machine.
// Code lifecycle: generated by user (15 min expiry) → consumed by webhook
// when user texts the bot. State stored on users table.
import { db, tx, nowLocal, offsetLocal } from '../db/connection.js';
import { getUserByPhoneAndName } from './userService.js';
import { getLineOfficialUrl, getLineOfficialId } from './discountService.js';
import { ApiError } from './registration.js';

const BIND_TTL_MINUTES = 15;
const CODE_GEN_RETRY = 10;

const getByCode = db.prepare(`
  SELECT id, line_user_id, line_bind_expires_at
  FROM users WHERE line_bind_code = ?
`);
const getByLineId = db.prepare('SELECT id FROM users WHERE line_user_id = ?');
const updateBindCode = db.prepare(`
  UPDATE users SET line_bind_code = ?, line_bind_expires_at = ? WHERE id = ?
`);
const completeBind = db.prepare(`
  UPDATE users
  SET line_user_id = ?, line_bind_code = NULL, line_bind_expires_at = NULL
  WHERE id = ?
`);
const clearLineByLineId = db.prepare(`
  UPDATE users SET line_user_id = NULL WHERE line_user_id = ?
`);
const clearLineByUserId = db.prepare(`
  UPDATE users
  SET line_user_id = NULL, line_bind_code = NULL, line_bind_expires_at = NULL
  WHERE id = ?
`);

function randomSixDigit() {
  return String(Math.floor(100000 + Math.random() * 900000));
}

/**
 * Generate a new 6-digit binding code for the given user.
 * Stores code + expiry on users row. Returns { code, expires_at }.
 */
export function generateBindCode(userId) {
  return tx(() => {
    let code;
    let found = false;
    for (let attempt = 0; attempt < CODE_GEN_RETRY; attempt++) {
      code = randomSixDigit();
      const dup = getByCode.get(code);
      if (!dup) {
        found = true;
        break;
      }
    }
    if (!found) {
      throw new Error('bind code generation exhausted retries; another user holds every candidate');
    }
    const expiresAt = offsetLocal(BIND_TTL_MINUTES * 60 * 1000);
    updateBindCode.run(code, expiresAt, userId);
    return { code, expires_at: expiresAt };
  });
}

/**
 * Webhook handler calls this when user texts a 6-digit code to the bot.
 * Returns one of:
 *   { outcome: 'bound', userId }
 *   { outcome: 'invalid_code' }
 *   { outcome: 'chinup_already_bound' }
 *   { outcome: 'this_line_already_bound' }
 */
export function consumeCode(code, lineUserId) {
  return tx(() => {
    const user = getByCode.get(code);
    if (!user) return { outcome: 'invalid_code' };
    if (!user.line_bind_expires_at || user.line_bind_expires_at < nowLocal()) {
      return { outcome: 'invalid_code' };
    }
    if (user.line_user_id) return { outcome: 'chinup_already_bound' };

    const occupier = getByLineId.get(lineUserId);
    if (occupier) return { outcome: 'this_line_already_bound' };

    completeBind.run(lineUserId, user.id);
    return { outcome: 'bound', userId: user.id };
  });
}

/**
 * Clear line_user_id for the chinup user bound to this LINE userId.
 * Called from webhook on `unfollow` event (user blocked / removed bot)
 * and from DELETE /api/my/line.
 */
export function unbindByLineUserId(lineUserId) {
  clearLineByLineId.run(lineUserId);
}

/**
 * Clear everything for the given chinup user.
 * Called from DELETE /api/my/line.
 */
export function unbindByUserId(userId) {
  clearLineByUserId.run(userId);
}

/**
 * 管理用：清空『所有』使用者的 LINE 綁定（line_user_id + 進行中的綁定碼），
 * 讓全體（含教練/管理者）重新綁定。回 { cleared } = 清空前已綁定(line_user_id 非空)的人數。
 */
export function resetAllLineBindings() {
  return tx(() => {
    const cleared = db.prepare('SELECT COUNT(*) AS c FROM users WHERE line_user_id IS NOT NULL').get().c;
    db.exec('UPDATE users SET line_user_id = NULL, line_bind_code = NULL, line_bind_expires_at = NULL');
    return { cleared };
  });
}

/**
 * 公開：客戶以 phone+name 自助產生綁定碼（我的課表頁用）。
 * 驗名 reader + role 守門（非 user 一律當查無，中性不洩員工）+ 已綁定 409。
 * 只回 { code, expires_at, line_official_url, line_official_id }，不回 user 列。
 */
export function requestPublicBindCode({ phone, name }) {
  const user = getUserByPhoneAndName({ phone, name });
  if (!user || user.role !== 'user') throw new ApiError(403, 'not_found_or_mismatch');
  if (user.line_user_id) throw new ApiError(409, 'already_bound');
  const { code, expires_at } = generateBindCode(user.id);
  return { code, expires_at, line_official_url: getLineOfficialUrl(), line_official_id: getLineOfficialId() };
}
